### ISSUE TITLE
[Bug] Crashes with other addons

### ISSUE THREAD

**Issue by CheatTerminator** [AntiCope/reaper-addon#4]
### Describe the bug

Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.client.main.Main.main(Main.java:206)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77)
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:102)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 11 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector breakBlockCheck(Lnet/minecraft/class_746;)Z in reaper.mixins.json:MincraftClientMixin from mod reaper failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap reaper-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 16 more

Tried to remove Meteor Tweaks, didn't work

### Steps to reproduce

```plaintext
1. Use Meteor Reaper Addon with other addons from anticope.ml
2. and that's all
```

### Operating System

Windows

### reaper Version

Latest

### Meteor Version

0.4.9-1470

### Minecraft Version

1.18.2

### Other mods

```plaintext
1. Fabric API
2. Meteor Additions
3. Meteor Crash Addon
4. Litematica Printer
5. Meteor Rejects
6. Meteor Tweaks (still crashes without it)
7. Meteor Utils
8. Notifications Addon
9. Orion
10. Silivia
11. Tanuki Addon
12. Vector Addon
13. Village roller
14. Sodium
15. Phosphor
```

**Comment by Declipsonator** [comment]
Try removing vector

**Comment by BookWyrm114** [comment]
I use reaper with vector, so that’s not the problem, however I have confirmed that it conflicts with both meteor tweaks and silivia.

**Comment by Declipsonator** [comment]
Are you on the latest version of everything?

**Comment by BookWyrm114** [comment]
Yes

**Comment by BookWyrm114** [comment]
They just have to remove meteor tweaks and silivia

**Comment by Declipsonator** [comment]
Vector is compatible with tweaks

**Comment by BookWyrm114** [comment]
I know it is, I’m saying that reaper isn’t compatible with tweaks or silivia

**Comment by Declipsonator** [comment]
Pretty sure the problem is silivia, just launched reaper and tweaks perfectly

**Comment by BookWyrm114** [comment]
Oh cool, silivia is incompatible with both reaper and tweaks, and I assumed that reaper and tweaks would also be incompatible, now I can use tweaks too.

**Comment by CheatTerminator** [comment]
ok cool, silivia doesn't have that many things anyway
